### ISSUE TITLE
Towns/Nations will not be created with new Gringotts version

### ISSUE THREAD

**Issue by OmegaShaman** [nikosgram13/Gringotts#83] opened 2021-12-15 21:39 UTC
**Describe the bug**
After doing /t new with money in my vault, the town is not made and it just takes the gold. This is the exact same with nations as well. The weirdest part is that nothing appears in the console when I run this command, so it's hard to report.

**To Reproduce**
Type /t new and /confirm

**Expected behavior**
It's supposed to take the gold, and make the new town.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/67159692/146269036-8bb60ec1-7773-4988-8dc0-d20b5a3541b9.png)

**Desktop (please complete the following information):**
 - Server Type: Purpur
 - Server Version: 1.17.1-hotfix
 - Gringotts Version: 2.12.2

**Comment by nikosgram** [comment] 2022-03-16 00:02
It should be fixed here:

8eea3fb2ee1673ba0a50397f5ab23affb678d0ee

Is it possible to test it out as I'm not able to reproduce it :) 

[gringotts-2.12.3.jar.zip](https://github.com/nikosgram/gringotts/files/8257950/gringotts-2.12.3.jar.zip)

**Comment by Darklom** [comment] 2022-09-02 19:59
With this new version @nikosgram - I've encountered the following issues described in [Towny #6148](https://github.com/TownyAdvanced/Towny/issues/6148#issuecomment-1235841403)

6. Your log's error:

Error 1 - [[05:27:44 ERROR]: Could not pass event PlayerDeathEvent to Towny v0.98.3.6
(optional) If this is to do with permissions,](https://pastebin.com/siWEMERw)

Error 2 - [On /town create test123](https://pastebin.com/QK85HJLc)

**Comment by nikosgram** [comment] 2022-09-02 23:51
Relevant information: https://github.com/TownyAdvanced/Towny/issues/6148#issuecomment-1235984575

I'll keep this issue updated for any changes. 

😄

**Comment by nikosgram** [comment] 2022-09-03 00:32
I just deployed a snapshot version of gringotts with possible the solution of the issue included, is it possible @Darklom or @Jqnnies to try reproduce the issue in that version? For some reason I cannot reproduce it myself.

https://github.com/nikosgram/gringotts/releases/download/2.12.3-SNAPSHOT/gringotts-2.12.3-SNAPSHOT.jar

Thank you <3

**Comment by nikosgram** [comment] 2022-09-04 17:57
Hello, 

Just to keep the thread up to date, I have recently moved towny's support to it's own repo and planning to release it as it's own plugin in spigot's website later next week :)

07d5be3325ca82189bbc8187d0aa0afd3f5749ff

https://github.com/nikosgram/gringotts-towny

**Comment by nikosgram** [comment] 2022-09-04 19:51
The relevant project: https://github.com/nikosgram/gringotts-towny

They are some issues that Gringotts had with Toeny that has been addressed in this plugin. Hopefully that also fixes this issue :)

**Closed as completed** 2023-07-21 20:50 UTC
Labels: bug
